#!/bin/bash

# checker library
MORPHEXT_HOME=$HOME/Projects/MorphExtensions/bin
LIB_NAME=morphextensions.jar
LIB_PATH=$MORPHEXT_HOME/$LIB_NAME

# classpath setup
CHECKERS_CP_PREFIX=/home/bibou/Projects/types/checker-framework/binary
CHECKERS=$CHECKERS_CP_PREFIX/checkers.jar
JAVAC=$CHECKERS_CP_PREFIX/javac.jar
JDK7=$CHECKERS_CP_PREFIX/jdk7.jar
CHECKER_CP=$CHECKERS:$JAVAC:$JDK7

# checker framework
ENABLED_CHECKERS=checkers.MorphChecker

# options for javac command
INPUT_FILES=
OPTIONS=
WHATIF=false

function usage
{
    echo "usage: javamc [-h] | [--whatif]] files"
}

if [ ! -f $LIB_PATH ]; then
    echo "error: morph extensions library not found or not generated."
    exit
fi

while [ "$1" != "" ]; do
    case $1 in
        -h | --help )
            usage
            exit
            ;;
        --whatif )
            WHATIF=true
            shift
            ;;
        *.java )
            INPUT_FILES="$INPUT_FILES $1"
            shift
            ;;
        * )
            shift
            ;;
    esac
done

COMMAND="javac -Xbootclasspath/p:$LIB_PATH:$CHECKER_CP -processorpath $LIB_PATH:$CHECKER_CP -processor $ENABLED_CHECKERS $INPUT_FILES"

if $WHATIF
then
    echo $COMMAND
else
    $COMMAND
fi
